apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rulio-operator
  source: rulio-operator
  sourceNamespace: openshift-marketplace