# permissions for end users to view rulesengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulesengine-viewer-role
rules:
- apiGroups:
  - rules.quay.io
  resources:
  - rulesengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rules.quay.io
  resources:
  - rulesengines/status
  verbs:
  - get
