# permissions for end users to edit rulesengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulesengine-editor-role
rules:
- apiGroups:
  - rules.quay.io
  resources:
  - rulesengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rules.quay.io
  resources:
  - rulesengines/status
  verbs:
  - get
