apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: rulio-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RulesEngine is the Schema for the rulesengines API
      displayName: Rules Engine
      kind: RulesEngine
      name: rulesengines.rules.quay.io
      version: v1alpha1
  description: this operator spins up and manages instances of rulio rules engine
  displayName: rulesengine
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - rulesengine
  links:
  - name: Rulio Operator
    url: https://rulio-operator.domain
  maturity: alpha
  provider:
    name: adam cornett
  version: 0.0.0
